// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5BbNwyfs55QRl_Ds4du5OwX7QR7s9NP8',
    appId: '1:378837946016:web:73df17bc5908d99f7603c5',
    messagingSenderId: '378837946016',
    projectId: 'flutter-firebase-auth-52473',
    authDomain: 'flutter-firebase-auth-52473.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-52473.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpOr_7k2WYGS2FTYi_M_DaNzx_PEyreOI',
    appId: '1:378837946016:android:b6e3ef71f61a5bab7603c5',
    messagingSenderId: '378837946016',
    projectId: 'flutter-firebase-auth-52473',
    storageBucket: 'flutter-firebase-auth-52473.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALd49HWnLnuh_v5MzLpewcCMao2relmk4',
    appId: '1:378837946016:ios:e5cc0a4b0a2d63237603c5',
    messagingSenderId: '378837946016',
    projectId: 'flutter-firebase-auth-52473',
    storageBucket: 'flutter-firebase-auth-52473.appspot.com',
    iosClientId: '378837946016-nucp7bnh83qkfviltuaee5id3aoct52c.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoChatApp',
  );
}
